### ISSUE TITLE
Permission to adapt & reuse the drama content in a Java mod?

### ISSUE THREAD

**Issue by desht** [elifoster/drama-rb#19]
Since this project doesn't appear to have a published licence, I thought it would be polite to ask: is it OK if I incorporate the data (in lib/drama/constants.rb) into an opensource Forge mod (PneumaticCraft: Repressurized to be exact) ?

The idea is to display a random drama string on the mod's Aphorism Tiles (like signs but better) when they're placed down. I have been retrieving content via http://mc-drama.herokuapp.com/raw, but occasional 500 errors and the general overhead of making HTTP requests make me think a completely local solution would be better.

Acknowledgement to this project would of course be given.

**Comment by elifoster** [comment]
That's fine by me. Most of that list was created by @asiekierka who I doubt minds either (from knowing them for almost a decade now — wow). 

But, just for the sake of comprehensiveness, some alternative ideas for you to consider: you could (a) have a set of default options when it errors; (b) cache the results and, if it errors, use one of the cached ones; (c) mix of both (a) and (c); (d) do what you're already planning, but so you don't have to keep the list updated manually in your mod source (it isn't updated often but it could be in theory) you could [download the constants list](https://raw.githubusercontent.com/elifoster/drama-rb/master/lib/drama/constants.rb) at startup and parse it.

By the way, does it error that often? I keep it working but haven't personally used my drama generator mod consistently in a long time.

**Comment by asiekierka** [comment]
I laughed that I deliberately left MinecraftDramaGenerator's repository without a license, as the "final drama" to come out of it... but realistically, I don't really care - I moved on from that project; the statement I intended to make at the time has been made, and large-scale drama nowadays certainly seems a lot more rare than it was in 2014.

**Comment by desht** [comment]
> By the way, does it error that often? I keep it working but haven't personally used my drama generator mod consistently in a long time.

I'd need to examine logs more carefully - I've seen a few 500 errors but I think it is pretty intermittent, and I've never actually placed down a tile and not had drama text appear on it.  So it's probably just the odd request out of a series of requests.

And it could be something I was doing wrong (fetching too quickly?  the current code pulls 10 requests into a buffer queue, sleeping for 5 seconds between requests, but if the queue gets too empty, it can send requests without a delay between...)

https://github.com/TeamPneumatic/pnc-repressurized/blob/1.16.4/src/main/java/me/desht/pneumaticcraft/common/util/DramaSplash.java

**Comment by elifoster** [comment]
That link doesn't work but I don't see why that would be wrong. Whatever the issue may be, it is probably due to me using the free tier of Heroku lol.
