### ISSUE TITLE
Overlap with fork sign and output

### ISSUE THREAD

**Issue by Strikingwolf** [elifoster/drama-rb#2]
<img width="1218" alt="screen shot 2015-10-27 at 6 54 30 pm" src="https://cloud.githubusercontent.com/assets/5892049/10776077/4e8938f0-7cdc-11e5-97f6-45cc044147de.png"></img>

That shouldn't happen should it :P

**Comment by elifoster** [comment]
Oh yeah, i saw that the other night but forgot to report it here :stuck_out_tongue: 

I'll get around to fixing that, should be pretty simple.

**Comment by Strikingwolf** [comment]
> Switches the `Get more drama!` link and the output

**Comment by elifoster** [comment]
That's kind of a bleh solution since I like the positioning of everything. I'll just limit how far the text spans with some CSS magics.

**Comment by Strikingwolf** [comment]
> Was kidding

**Comment by elifoster** [comment]
:joy:
